---
language: ruby

cache: bundler

before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v

sudo: false

script: 'SPEC_OPTS="--format documentation" bundle exec rake validate lint spec'

matrix:
  fast_finish: true
  include:
  - rvm: 2.5.1
    env: PUPPET_GEM_VERSION="~> 6"
  - rvm: 2.7.3
    env: PUPPET_GEM_VERSION="~> 7"

notifications:
  email: false
